[package]
name = "j-webgl-macro-make-renderer"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = [ "full", "extra-traits" ] }
proc-macro2 = { version = "1" }
quote = { version = "1" }
